Rspec dev
o-rashad/private-events pull request #1
Opened 2021-06-10 19:06 UTC by od-c0d3r

built an application named Private Events and that behaves similar to Eventbrite events management web application

2021-06-10 23:27 UTC, BrianSammit requested changes
CHANGES REQUIRED :red_circle: :stop_sign: 
--------------------
Hello @od-c0d3r @tanzila-abedin great job you did on this project :muscle: 
TO HIGHLIGHT: 

- The repo is professional
- The project is professional 
- Well structured files 
- Well use of the MVP 

However, there are a few changes to make to complete this project :hammer_and_wrench: see them below :eyes: :point_down: 
----------------

- [ ] Check the commit messages. Remember that you must write them with the [formating](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules) rules. You don't need to make the changes this time but keep these formating rules in mind for the next commits. 
- [ ] I cannot sign out. Please add the link at the top to be able to sign out. 
- [ ] I only can see links to `All Events` and `My events` there is no link to create a new event.
- [ ] I cannot create a new event. 

![Screenshot from 2021-06-10 17-40-23](https://user-images.githubusercontent.com/64173189/121605966-f2ffbb00-ca12-11eb-8b9f-f7fcd32abf33.png)

- [ ] In your event controller in index action you need to list the event in past events, E.g `@past_events = Event.previous_events` and ucomping events, E.g `@upcoming_events = Event.upcoming_events`

![past_upcoming_events_requirement](https://user-images.githubusercontent.com/64173189/121607903-7f5fad00-ca16-11eb-85ae-9bfb8dc81fa6.png)

- [ ] On the user's show page that you called My events. displays events the user has created and events that the user is attending to separated in past and upcoming.

- [ ] In your user's controller in show action you need to list events previoulsy attendented by user using event model scope, E.g `@past_events = current_user.attended_events.previous` and upcoming events previously attended by user using event model scope, E.g `@upcoming_events = current_user.attended_events.upcoming`

![user_events_requirement (1)](https://user-images.githubusercontent.com/64173189/121608129-f006c980-ca16-11eb-9334-128e6036d7e5.png)

- [ ] On My events I can attend a past event.  

-------------
 Make these required changes and send it again for another review :muscle: :100: 
Reach me on SLACK if you have any questions
@ Brian Sammit Cruz Rodriguez

HAPPY CODING !!!!

![AngelicConcreteHypsilophodon-max-1mb](https://user-images.githubusercontent.com/64173189/121609334-352bfb00-ca19-11eb-8a47-02306b0e4cb7.gif)

2021-06-11 00:48 UTC, od-c0d3r commented
Thanks @BrianSammit for the review ⭐️⭐️⭐️
We @tanzila-abedin gonna work on 
the required changes and push ASAP.

2021-06-11 16:11 UTC, BrianSammit requested changes
CHANGES REQUIRED :red_circle: 
--------
Hello there again :wave: Great job working on the required changes :+1: :100: 
However, there is a minor change to make :wrench: 
--------------

- [ ] There is a bug that is not letting me create a new event. I need to change the controller to make it work but once I change the user the error continues. 

![Screenshot from 2021-06-11 11-06-37](https://user-images.githubusercontent.com/64173189/121715994-20954480-caa5-11eb-8bef-c509e3d8888a.png)

![Screenshot from 2021-06-11 11-07-50](https://user-images.githubusercontent.com/64173189/121716129-46bae480-caa5-11eb-92f2-7578c32e3fd5.png)

----------------
Fix this bug on your app and send it again for another review :100: :+1: 
HAPPY CODING !!!

![tenor (1)](https://user-images.githubusercontent.com/64173189/121716415-9bf6f600-caa5-11eb-995d-5014b099f928.gif)

2021-06-11 17:17 UTC, od-c0d3r commented
@BrianSammit Thanks again ^^, 
We will reach out to you, cuz the bug
is not occurring on my end.

![tenor (1)](https://media.giphy.com/media/EtB1yylKGGAUg/giphy.gif)

2021-06-11 19:38 UTC, enaburekhan requested changes
# Status: Changes required:wrench::hammer::full_moon:
**Hi team!
Great job so far:clap::clap:. we are almost there. We just need to make a few changes to get the project approved:muscle:.**

**To improve**

- [x] App behavior

- I succeeded in creating just one event. And I couldn't create subsequent events. whether `past` or `upcoming`. I keep getting this [error](https://imgur.com/a/eyWA6t3). Re-check the codes, especially the codes in the controller and fix this bug.

- [x] Controller

- Check my inline comments below and make the required changes.

- [x] Database

- an index for `event_id` column is added to the `tokens` table
- an index for `user_id` column is also added to the `tokens`  table

Why indices for foreign keys are necessary? In short: Since the foreign key columns will be used often to retrieve related information, it's important to index them (queries on those columns will be faster with indexes). More details: check this [article](
https://semaphoreci.com/blog/2017/05/09/faster-rails-is-your-database-properly-indexed.html) and this [article](https://sqlperformance.com/2012/11/t-sql-queries/benefits-indexing-foreign-keys).

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

2021-06-11 19:38 UTC, enaburekhan commented on app/controllers/events_controller.rb
> +    @event = current_user.events.create(user_params)
- [ ] uses #build method on association, i.e. `current_user.events.build(event_params)` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/build_method_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)).
Kindly edit the highlighted line of code to reflect :point_up:

2021-06-11 19:38 UTC, enaburekhan commented on app/controllers/events_controller.rb
> +    @past_events = @events.past
- [ ] Refactor this code: Currently, the implementation seems difficult to understand. I believe it should be similar to this:
@future_events = Event.upcoming
@past_events = Event.past

2021-06-12 16:54 UTC, od-c0d3r commented
Thank you @enaburekhan for the review ^^!
We worked on the changes.
The app works fine now.

2021-06-12 18:20 UTC, rindrajosia requested changes
Changes Required :red_circle:
To Highlight: :angel:

- Logged in user can create a new upcoming event  :+1: 

To improve :factory_worker: [REQUIRED]:

- [ ] In your event controller in index action you need to list the event in past events, E.g @past_events = Event.upcoming and ucomping events, E.g @upcoming_events = Event.past ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))(Please check my inline comments below :arrow_double_down: )
- [ ] an index for `creator_id, attendee_id and event_id` columns should added. Since the foreign key columns will be used often to retrieve related information, it's important to index them (queries on those columns will be faster with indexes).

- [ ] I cannot create Past events. Please fix it.
![1](https://user-images.githubusercontent.com/58552748/121785268-7bbc5980-cbc1-11eb-93d9-72e17d419db3.gif)
![1](https://user-images.githubusercontent.com/58552748/121785391-3c423d00-cbc2-11eb-966f-73bfdaf60f76.gif)

- [ ] Please, remove **Attend link**  when user is not `logged in `because only `logged in` user can attend events.
![1](https://user-images.githubusercontent.com/58552748/121785537-f5a11280-cbc2-11eb-9f9a-ed2251992778.png)


Nice to have:

- [ ] routes only for used actions, `i.e. resources :events, only: [:new, :create, :show, :index]`

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-06-12 18:20 UTC, rindrajosia commented on app/controllers/events_controller.rb
> +    @past_events = Event.all.past
Refactor this code: Currently, the implementation seems difficult to understand. I believe it should be similar to this:
@future_events = Event.upcoming
@past_events = Event.past

2021-06-12 18:20 UTC, rindrajosia commented on README.md
> +
[OPTIONAL] Please ask user to create db via `rails db:create `before migration

2021-06-12 18:20 UTC, rindrajosia commented on README.md
> +```
[OPTIONAL] You can ask the user to use command `rails s `after migration to open your app.

2021-06-12 19:56 UTC, oloomoses approved these changes
# Congratulations, Project Approved. :muscle: :tada: :clap: 
**Hello team,
Great job working on the suggested changes from the previous review.
You have passed all the requirements for this project :muscle: 
Feel free to merge and close this pull request.**

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

2021-06-12 20:18 UTC, merged